[package]
name = "risc-v-sim-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["multipart"] }
tokio = { version = "1.48.0", features=[ "rt-multi-thread" ] }
tempfile = "3.19.1"
serde_json = "1.0"
