services:
  riscv-sim-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riscv-sim-web
    restart: unless-stopped
    network_mode: host
    environment:
      - MONGODB_URI=mongodb://localhost:27017
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./submission:/app/submission
